[build]
  command = "npx eleventy"
  publish = "_site"
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
[[headers]]
  for = "/img/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"
[[headers]]
  for = "/img/*.png"
  [headers.values]
    Content-Type = "image/png"
[[headers]]
  for = "/img/*.webp"
  [headers.values]
    Content-Type = "image/webp"
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
[[headers]]
  for = "/img/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    [[redirects]]
  from = "/submit-profile"
  to = "/submit-profile/"
  status = 301
  [build]
  command = "npx @11ty/eleventy"
  publish = "_site"
  functions = "functions"
